### ISSUE TITLE
String with "something" in it

### ISSUE THREAD

**Issue by zoffixznet** [bradclawsie/Subsets-Common#2]
Can't propose a good name, but a very common type is a string with "something"; that is a string with some non-whitespace characters. It's call that a `NonEmptyStr` rather than merely the string with `.chars` that you already have.

`subset ValueStr of Str where /\S/;`

**Comment by bradclawsie** [comment]
good point, I'll make a fix soon!

**Comment by briandfoy** [comment]
This appears to have to fixed.

**Comment by zoffixznet** [comment]
> This appears to have to fixed.

I don't see it. There's no subset that checks for string with something other than whitespace in it.

**Comment by bradclawsie** [comment]
Zoffix is right, I had forgotten about these bugs, my bad, fixed.
